version: '3.8'

services:
  node-api:
    container_name: node-api-container
    build: .
    image: clean-node-api
    restart: always
    command: npm run debug
    volumes:
      - ./dist:/usr/app/clean-architecture-api/dist
      - ./package.json:/usr/app/clean-architecture-api/package.json
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
      - PORT=5050
    ports:
      - '5050:5050'
      - '9222:9222'
    links:
      - mongo

  mongo:
    container_name: mongo-container
    image: mongo
    restart: always
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    volumes:
      - ~/.MongoData/mongo_clean_arc_api:/data/db
    ports:
      - '27017:27017'
