version: '3.8'

services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    volumes:
      - ~/.MongoData/mongo_clean_arc_api:/data/db
    ports:
      - '27017:27017'
